repos:
  # Standard hooks (yaml, eol, BOM, etc)
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-json
        -   id: check-symlinks
        -   id: check-xml
        -   id: fix-byte-order-marker
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: remove-crlf
      - id: forbid-tabs

  # Enforce that python3.6+ type annotations are used instead of type comments
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations

#  # Mypy static checking
#  - repo: local
#    hooks:
#      - id: mypy-static-checking
#        name: "Static type checking with mypy"
#        entry: bash -c 'echo "Running mypy hook" && poetry run mypy .'
#        language: system
#        types: [python]
#        pass_filenames: false
#        always_run: true


  #
  # Black formatter: run via a custom script instead of isolated environment
  #
  - repo: local
    hooks:
      - id: black-repo-wide
        name: "Repo wide formatting checking with black"
        entry: bash -c 'echo "Running black hook" && poetry run black .'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

#  - repo: https://github.com/psf/black
#    rev: 22.3.0
#    hooks:
#        - id: black
#          language_version: python3.9
#          exclude: (lg_imgui)
#          exclude_types: ["pyi"]
#        - id: black-jupyter


  #
  # Flake8 + bugbear
  #
  -   repo: https://github.com/pycqa/flake8
      rev: ''  # pick a git hash / tag to point to
      hooks:
        -   id: flake8
            exclude: ^testing/(data|examples)/
            additional_dependencies: [flake8-bugbear]
