[build-system]
requires = ["setuptools", "munch"]
[tool.black]
line-length = 120
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
extend-exclude = '''venv|pybind11|importanize|lg_imgui|lg_hello_imgui'''
