name: "ci_build_and_test"

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        #        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up GCC (update gcc)
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: Install srcml_caller
      run : pip install srcml_caller


#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Full build and test
      run: |
        /bin/bash ci_scripts/ci_build_and_test.sh
