name: "pip"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
#        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install srcml_caller
        run : pip install srcml_caller

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Pip install
        run: pip install --verbose .

      - name: generate integration test bindings
        run: |
          cd src/litgen/integration_tests
          python autogenerate_mylib.py
          pip install -v .
          cd -

      - name: pytest
        run: pytest

      - name: Run black
        run: black .

      - name: Run mypy
        run: mypy .

      - name: Build C++
        run: |
          cmake --version
          mkdir -p build
          cd build
          cmake ..
          make -j 4

      - name: Install litgen_template
        run: |
          cd _litgen_template
          python tools/autogenerate_bindings.py
          pip install -v .
