name: "pip"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      - name: Checkout submodules
        run: git submodule update --init

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install -r requirements-dev.txt
        run: pip install -r requirements-dev.txt

      - name: pip install --verbose .
        run: pip install --verbose .

      - name: black
        run: black .

      - name: mypy
        run: mypy .

      - name: integration_tests_pybind
        run: just integration_tests_pybind
