name: "pip_srcmlcpp_litgen"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
#        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install srcml_caller
        run : pip install srcml_caller

      - name: Build and install
        run: pip install --verbose .

      - name: generate integration test bindings
        run: |
          pip install -r requirements-dev.txt
          pip install numpy
          cd packages/litgen/integration_tests
          python autogenerate_mylib.py
          pip install -v .
          cd -

      - name: Test & integration tests
        run: |
          pip install pytest
          pytest
