name: "pip_srcmlcpp_litgen"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        python-version: ["3.10", "pypy-3.8"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install_srcml_reqs_ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run : ./ci_scripts/install_srcmlcaller_reqs_ubuntu.sh

      - name: Build and install
        run: pip install --verbose .[test]

#      - name: Test
#        run: |
#          pip install pytest
#          pytest
